### ISSUE TITLE
[BUG] executable removed from releases

### ISSUE THREAD

**Issue by andreineculau** [NorthboundTrain/jqg#6]
**Describe the bug**

Executable removed from releases, therefore README instructions are failing

`wget https://github.com/NorthboundTrain/jqg/releases/latest/download/src/jqg`

---
**Versions & Environments**
N/A

---
**To Reproduce**
N/A

---
**Additional Context**
N/A

**Comment by NorthboundTrain** [comment]
Thanks for pointing that out -- I'm not sure when/how that broke, nor how to fix it using the "latest" release tag. It seems like it can't be done with a simple link, so I'll substitute in a branch-specific link:

https://raw.githubusercontent.com/NorthboundTrain/jqg/main/src/jqg

**Comment by NorthboundTrain** [comment]
Also, this line doesn't work:

`git clone git@github.com/NorthboundTrain/jqg.git`

it should be:

`git clone git@github.com:NorthboundTrain/jqg.git`

(first '`/`' is a '`:`')
